version: "3.9"

services:
  api-gateway:
    build:
      context: ./api-gateway
    ports:
      - "3000:3000"
    depends_on:
      - ml-service
      - mongo
    environment:
      - NODE_ENV=production
      - MONGO_URI=mongodb+srv://vasireddylokesh3_db_user:JsMdMMr5j1w1VJdR@cluster0.don7c03.mongodb.net/?appName=Cluster0/ipl_db
    restart: unless-stopped

  ml-service:
    build:
      context: ./ml-service
    ports:
      - "5001:5000"
    volumes:
      - ./models:/app/models
    environment:
      - ENV=production
    restart: unless-stopped

  mongo:
    image: mongo:6-jammy
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db
    restart: unless-stopped

volumes:
  mongo_data: